<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="PC201603201541" name="com.zuora.test.exam.testcases.DealsTest" tests="10" failures="1" timestamp="04 六月 2018 13:24:21 GMT" time="8.309" errors="0">
  <testcase name="testCreateDealsValid" time="2.874" classname="com.zuora.test.exam.testcases.DealsTest"/>
  <testcase name="testCreateDealsInvalid" time="0.489" classname="com.zuora.test.exam.testcases.DealsTest"/>
  <testcase name="testCreateDealsWrongFormat" time="0.559" classname="com.zuora.test.exam.testcases.DealsTest"/>
  <testcase name="testListDealsValid" time="1.375" classname="com.zuora.test.exam.testcases.DealsTest"/>
  <testcase name="testListDealsInValid" time="0.532" classname="com.zuora.test.exam.testcases.DealsTest"/>
  <testcase name="updateDealValid" time="0.516" classname="com.zuora.test.exam.testcases.DealsTest">
    <failure type="java.lang.AssertionError" message="expected:&lt;400&gt; but was:&lt;200&gt;">
      <![CDATA[java.lang.AssertionError: expected:<400> but was:<200>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
at com.zuora.test.exam.util.TestBase.executePutCommonCases(TestBase.java:52)
at com.zuora.test.exam.testcases.DealsTest.updateDealValid(DealsTest.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- updateDealValid -->
  <testcase name="updateDealInValid" time="0.454" classname="com.zuora.test.exam.testcases.DealsTest"/>
  <testcase name="updateDealWrongFormat" time="0.474" classname="com.zuora.test.exam.testcases.DealsTest"/>
  <testcase name="deleteDealInValid" time="0.466" classname="com.zuora.test.exam.testcases.DealsTest"/>
  <testcase name="deleteDealValid" time="0.570" classname="com.zuora.test.exam.testcases.DealsTest"/>
</testsuite> <!-- com.zuora.test.exam.testcases.DealsTest -->
